### ISSUE TITLE
SyntaxError: Unexpected end of JSON input at JSON.parse

### ISSUE THREAD

**Issue by fzamacolam** [oyve/signalk-barometer-trend#20]
Many many thanks for the plugin.

I have an issue, probably because I install and reinstall it. The variables 1hr, 3hr, 6hr, ... has a null value.
I reinstall again and the first error at the server log, when I configure the plugin is:

Nov 26 18:44:14 signalk-barometer-trend:Could not parse JSON :
Nov 26 18:44:14 signalk-barometer-trend:SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Object.JSONParser (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:182:17) at read (/home/pi/.signalk/node_modules/signalk-barometer-trend/index.js:97:34) at Object.populate (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:172:25) at plugin.start (/home/pi/.signalk/node_modules/signalk-barometer-trend/index.js:24:19) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:305:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:490:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:171:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:477:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:149:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:119:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10)
Nov 26 18:44:14 POST /skServer/plugins/signalk-barometer-trend/config 200 17.817 ms - 56
...

Now, every one minute the message is:

Nov 27 16:53:39 TypeError: Cannot read properties of undefined (reading 'predictions') at Object.getPrediction (/home/pi/.signalk/node_modules/barometer-trend/predictions/byPressureTrendAndSeason.js:10:33) at Object.getPredictions (/home/pi/.signalk/node_modules/barometer-trend/index.js:98:53) at onPressureUpdated (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:131:31) at Object.handle (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:41:84) at /home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:84:46 at Array.forEach (<anonymous>) at /home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:80:18 at Array.forEach (<anonymous>) at Object.onDeltasUpdate (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:76:20) at /home/pi/.signalk/node_modules/signalk-barometer-trend/index.js:37:42 at /usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:1048:16 at /usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:463:23 at processAfters (/usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:359:11) at Object.inTransaction (/usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:439:9) at Dispatcher.push (/usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:1214:24) at buffer.push (/usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:2030:21)
Nov 27 16:54:15 Handle: {"path":"navigation.position","value":{"longitude":-4.082283666666667,"latitude":40.709644833333336}}
Nov 27 16:54:15 Handle: {"path":"navigation.gnss.antennaAltitude","value":1095.9}
Nov 27 16:54:22 Handle: {"path":"environment.outside.temperature","value":294.0875}
Nov 27 16:54:35 [object Object]
Nov 27 16:54:39 Front pattern: FRR

Many thanks in advance!

**Comment by oyve** [comment]
Try delete the file offline.json, and restart.

**Comment by fzamacolam** [comment]
The error still remains.

Nov 28 11:51:08 signalk-barometer-trend:Could not parse JSON :
Nov 28 11:51:08 signalk-barometer-trend:SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Object.JSONParser (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:182:17) at read (/home/pi/.signalk/node_modules/signalk-barometer-trend/index.js:97:34) at Object.populate (/home/pi/.signalk/node_modules/signalk-barometer-trend/barometer.js:172:25) at plugin.start (/home/pi/.signalk/node_modules/signalk-barometer-trend/index.js:24:19) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:305:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:490:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:171:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:477:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:149:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:119:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10)

**Comment by oyve** [comment]
@fzamacolam Did you delete the correct file? There is probably one in the source code directory (not in use), and one in another folder where offline data is stored per NPM module. I don't have a SignalK setup as we speak, and I can't remember what the folder structure is.

**Comment by fzamacolam** [comment]
I reinstalled the server from the scratch but the problem persist. ¿Could be the latest release of signalk?
In the end I have abandoned the project. I'll explore other alternatives. 
Thanks!!
